# Generated by Django 4.2.3 on 2023-08-31 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pickUpOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('creationDate', models.DateField()),
                ('pickUpDate', models.DateField()),
                ('deliveryDate', models.DateField()),
                ('date', models.DateField()),
                ('issuedByKey', models.CharField(blank=True, max_length=200, null=True)),
                ('destinationAgentKey', models.CharField(blank=True, max_length=200, null=True)),
                ('employeekey', models.CharField(blank=True, max_length=200, null=True)),
                ('shipperkey', models.TextField(blank=True, null=True)),
                ('PickUpLocationkey', models.TextField(blank=True, null=True)),
                ('consigneekey', models.TextField(blank=True, null=True)),
                ('deliveryLocationkey', models.CharField(blank=True, max_length=200, null=True)),
                ('inlandCarrier', models.CharField(blank=True, max_length=200, null=True)),
                ('mainCarrierKey', models.CharField(blank=True, max_length=200, null=True)),
                ('proNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('trackingNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('supplierKey', models.CharField(blank=True, max_length=200, null=True)),
                ('invoiceNumber', models.CharField(blank=True, max_length=200, null=True)),
                ('purchaseOrderNum', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='pieces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.FloatField(blank=True, default=0, null=True)),
                ('package', models.FloatField(blank=True, default=0, null=True)),
                ('description', models.FloatField(blank=True, default=0, null=True)),
                ('pieces', models.FloatField(blank=True, default=0, null=True)),
                ('length', models.FloatField(blank=True, default=0, null=True)),
                ('height', models.FloatField(blank=True, default=0, null=True)),
                ('width', models.FloatField(blank=True, default=0, null=True)),
                ('weight', models.FloatField(blank=True, default=0, null=True)),
                ('volume', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
    ]
