# Generated by Django 4.2.3 on 2023-08-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pickUpOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('shipper', models.TextField(blank=True, null=True)),
                ('consignee', models.TextField(blank=True, null=True)),
                ('PickUpOrder', models.TextField(blank=True, null=True)),
                ('deliveryName', models.CharField(blank=True, max_length=200, null=True)),
                ('piedes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('carrier', models.CharField(blank=True, max_length=200, null=True)),
                ('weight', models.FloatField(blank=True, default=0, null=True)),
                ('volume', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
    ]
