# Generated by Django 4.2.3 on 2023-12-04 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
        ('wareHouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='receptionSupplier', to='maintenance.carrier'),
        ),
    ]
