# Generated by Django 4.2.3 on 2023-08-31 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
        ('wareHouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuporder',
            name='employeekey',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.employee'),
        ),
    ]
