# Generated by Django 5.0.4 on 2024-06-03 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareHouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuporder',
            name='volumen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pickuporder',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receptionorder',
            name='volumen',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
