# Generated by Django 4.2.3 on 2023-09-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareHouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
