# Generated by Django 4.2.3 on 2024-07-05 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareHouse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pickuporder',
            old_name='creation_fecha',
            new_name='creation_date_text',
        ),
        migrations.AddField(
            model_name='pickuporder',
            name='delivery_date_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pickuporder',
            name='pick_up_date_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
