# Generated by Django 5.0.4 on 2024-07-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareHouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuporder',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pickuporder',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pickuporder',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pickuporder',
            name='pick_up_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
