# Generated by Django 4.2.3 on 2023-08-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareHouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuporder',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
