# Generated by Django 4.2.3 on 2023-12-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wareHouse", "0002_alter_releaseorder_client_to_bill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pickuporder",
            name="id",
            field=models.AutoField(default=80000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="receptionorder",
            name="id",
            field=models.AutoField(default=90000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="releaseorder",
            name="id",
            field=models.AutoField(default=70000, primary_key=True, serialize=False),
        ),
    ]
