# Generated by Django 4.2.3 on 2023-09-06 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wareHouse', '0002_prueba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='prueba',
        ),
    ]
