# Generated by Django 5.0.4 on 2024-10-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareHouse', '0002_receptionorder_inland_carrier'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuporder',
            name='carrier_charges',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
