# Generated by Django 5.0.4 on 2024-07-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareHouse', '0002_alter_pickuporder_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptionorder',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='releaseorder',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='releaseorder',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
