# Generated by Django 4.2.3 on 2023-09-25 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_remove_shipper_agent_remove_shipper_customer_and_more'),
        ('wareHouse', '0003_alter_pickuporder_shipper_delete_shipper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuporder',
            name='shipper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shipper', to='maintenance.vendor'),
        ),
    ]
