# Generated by Django 4.2.3 on 2023-11-10 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("maintenance", "0002_clienttobill_agent_clienttobill_agentid_and_more"),
        ("wareHouse", "0003_releaseorder_charges"),
    ]

    operations = [
        migrations.AddField(
            model_name="pickuporder",
            name="client_to_bill",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="pickUpclientToBill",
                to="maintenance.clienttobill",
            ),
        ),
    ]
