# Generated by Django 4.2.3 on 2023-09-15 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_alter_customer_typeperson'),
        ('wareHouse', '0003_delete_prueba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuporder',
            name='issuedByKey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='issuedBy', to='maintenance.forwardingagents'),
        ),
    ]
