# Generated by Django 4.2.3 on 2023-09-22 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wareHouse', '0003_delete_prueba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverylocation',
            name='agentName',
        ),
        migrations.RemoveField(
            model_name='deliverylocation',
            name='carrierName',
        ),
        migrations.RemoveField(
            model_name='deliverylocation',
            name='customerName',
        ),
        migrations.RemoveField(
            model_name='deliverylocation',
            name='vendorName',
        ),
        migrations.RemoveField(
            model_name='issuedby',
            name='forWardingAgents',
        ),
        migrations.RemoveField(
            model_name='issuedby',
            name='wareHouseProvider',
        ),
        migrations.RemoveField(
            model_name='pickuplocation',
            name='agentName',
        ),
        migrations.RemoveField(
            model_name='pickuplocation',
            name='customerName',
        ),
        migrations.RemoveField(
            model_name='pickuplocation',
            name='vendorName',
        ),
        migrations.RemoveField(
            model_name='shipper',
            name='agentName',
        ),
        migrations.RemoveField(
            model_name='shipper',
            name='customerName',
        ),
        migrations.RemoveField(
            model_name='shipper',
            name='vendorName',
        ),
        migrations.DeleteModel(
            name='consignee',
        ),
        migrations.DeleteModel(
            name='deliveryLocation',
        ),
        migrations.DeleteModel(
            name='issuedBy',
        ),
        migrations.DeleteModel(
            name='pickUpLocation',
        ),
        migrations.DeleteModel(
            name='shipper',
        ),
    ]
