# Generated by Django 4.2.3 on 2023-09-22 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_agent_packagetype_delete_address_delete_addressinfo_and_more'),
        ('wareHouse', '0004_remove_deliverylocation_agentname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pickuporder',
            old_name='creationDate',
            new_name='creation_date',
        ),
        migrations.RenameField(
            model_name='pickuporder',
            old_name='deliveryDate',
            new_name='delivery_date',
        ),
        migrations.RenameField(
            model_name='pickuporder',
            old_name='employeekey',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='pickuporder',
            old_name='inlandCarrierKey',
            new_name='inland_carrier',
        ),
        migrations.RenameField(
            model_name='pickuporder',
            old_name='invoiceNumber',
            new_name='invoice_number',
        ),
        migrations.RenameField(
            model_name='pickuporder',
            old_name='mainCarrierKey',
            new_name='main_carrier',
        ),
        migrations.RenameField(
            model_name='pickuporder',
            old_name='pickUpDate',
            new_name='pick_up_date',
        ),
        migrations.RenameField(
            model_name='pickuporder',
            old_name='proNumber',
            new_name='pro_number',
        ),
        migrations.RenameField(
            model_name='pickuporder',
            old_name='purchaseOrderNum',
            new_name='purchase_order_number',
        ),
        migrations.RenameField(
            model_name='pickuporder',
            old_name='supplierKey',
            new_name='supplier',
        ),
        migrations.RenameField(
            model_name='pickuporder',
            old_name='trackingNumber',
            new_name='tracking_number',
        ),
        migrations.RemoveField(
            model_name='pickuporder',
            name='PickUpLocationkey',
        ),
        migrations.RemoveField(
            model_name='pickuporder',
            name='consigneekey',
        ),
        migrations.RemoveField(
            model_name='pickuporder',
            name='deliveryLocationkey',
        ),
        migrations.RemoveField(
            model_name='pickuporder',
            name='destinationAgentKey',
        ),
        migrations.RemoveField(
            model_name='pickuporder',
            name='issuedByKey',
        ),
        migrations.RemoveField(
            model_name='pickuporder',
            name='shipperkey',
        ),
        migrations.AddField(
            model_name='pickuporder',
            name='consignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='consigneekey', to='maintenance.customer'),
        ),
        migrations.AddField(
            model_name='pickuporder',
            name='delivery_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deliveryLocation', to='maintenance.customer'),
        ),
        migrations.AddField(
            model_name='pickuporder',
            name='destination_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.agent'),
        ),
        migrations.AddField(
            model_name='pickuporder',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='issuedBy', to='maintenance.agent'),
        ),
        migrations.AddField(
            model_name='pickuporder',
            name='pick_up_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pickUpLocation', to='maintenance.customer'),
        ),
        migrations.AddField(
            model_name='pickuporder',
            name='shipper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shipper', to='maintenance.customer'),
        ),
    ]
