# Generated by Django 4.2.3 on 2023-09-25 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_shipper'),
        ('wareHouse', '0004_alter_pickuporder_shipper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuporder',
            name='shipper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shipper', to='maintenance.shipper'),
        ),
    ]
