# Generated by Django 4.2.3 on 2024-01-11 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("maintenance", "0001_initial"),
        ("wareHouse", "0004_alter_pickuporder_id_alter_receptionorder_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "tracking_number",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("store", models.CharField(blank=True, max_length=200, null=True)),
                ("courier", models.CharField(blank=True, max_length=200, null=True)),
                ("packages", models.JSONField(blank=True, null=True)),
                ("disabled", models.BooleanField(default=False)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="alertClient",
                        to="maintenance.customer",
                    ),
                ),
            ],
        ),
    ]
