# Generated by Django 4.2.3 on 2023-08-31 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
        ('wareHouse', '0004_alter_pickuporder_inlandcarrier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickuporder',
            name='mainCarrierKey',
        ),
        migrations.AlterField(
            model_name='pickuporder',
            name='inlandCarrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.carrier'),
        ),
        migrations.AlterField(
            model_name='pickuporder',
            name='supplierKey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.customer'),
        ),
        migrations.CreateModel(
            name='carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainCarrierKey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.carrier')),
            ],
        ),
    ]
