# Generated by Django 4.2.3 on 2024-04-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wareHouse", "0004_alter_pickuporder_id_alter_receptionorder_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="receptionorder",
            name="weight",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
