# Generated by Django 4.2.3 on 2023-09-25 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_deliverylocation_consignee'),
        ('wareHouse', '0005_alter_pickuporder_shipper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuporder',
            name='pick_up_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pickUpLocation', to='maintenance.pickuplocation'),
        ),
    ]
