# Generated by Django 4.2.3 on 2023-08-31 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareHouse', '0005_remove_pickuporder_maincarrierkey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuporder',
            name='mainCarrierKey',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='carrier',
        ),
    ]
