# Generated by Django 5.0.4 on 2024-06-06 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wareHouse', '0002_pickuporder_volumen_pickuporder_weight_and_more'),
        ('wareHouse', '0005_receptionorder_weight'),
    ]

    operations = [
    ]
