# Generated by Django 4.2.3 on 2023-09-25 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_deliverylocation_consignee'),
        ('wareHouse', '0006_alter_pickuporder_pick_up_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuporder',
            name='consignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='consigneekey', to='maintenance.consignee'),
        ),
        migrations.AlterField(
            model_name='pickuporder',
            name='delivery_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='deliveryLocation', to='maintenance.deliverylocation'),
        ),
    ]
