# Generated by Django 4.2.3 on 2023-10-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareHouse', '0007_alter_pickuporder_consignee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuporder',
            name='charges',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pickuporder',
            name='commodities',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
