# Generated by Django 4.2.6 on 2023-10-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareHouse', '0007_alter_pickuporder_deliverylocationkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuporder',
            name='commodities',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
