# Generated by Django 4.2.3 on 2023-10-03 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_consignee_agentid_consignee_carrierid_and_more'),
        ('wareHouse', '0008_pickuporder_charges_pickuporder_commodities'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceptionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('creation_date', models.DateField(blank=True, null=True)),
                ('consignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='receptionConsignee', to='maintenance.consignee')),
                ('destination_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='receptionDestinationAgent', to='maintenance.agent')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.employee')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.agent')),
                ('main_carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='receptionCarrier', to='maintenance.carrier')),
                ('shipper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='receptionShipper', to='maintenance.shipper')),
            ],
        ),
        migrations.DeleteModel(
            name='pieces',
        ),
        migrations.AlterField(
            model_name='pickuporder',
            name='consignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pickUpConsignee', to='maintenance.consignee'),
        ),
        migrations.AlterField(
            model_name='pickuporder',
            name='destination_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pickUpDestinationAgent', to='maintenance.agent'),
        ),
        migrations.AlterField(
            model_name='pickuporder',
            name='inland_carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inlandCarrier', to='maintenance.carrier'),
        ),
        migrations.AlterField(
            model_name='pickuporder',
            name='main_carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pickUpCarrier', to='maintenance.carrier'),
        ),
        migrations.AlterField(
            model_name='pickuporder',
            name='shipper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pickUpShipper', to='maintenance.shipper'),
        ),
    ]
