# Generated by Django 4.2.3 on 2023-10-03 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0009_clienttobill'),
        ('wareHouse', '0009_receptionorder_delete_pieces_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionorder',
            name='attachments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receptionorder',
            name='client_to_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clientToBill', to='maintenance.clienttobill'),
        ),
        migrations.AddField(
            model_name='receptionorder',
            name='commodities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receptionorder',
            name='events',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
