# Generated by Django 4.2.3 on 2023-10-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wareHouse', '0010_receptionorder_attachments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptionorder',
            name='charges',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receptionorder',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='receptionorder',
            name='notes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receptionorder',
            name='pro_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='receptionorder',
            name='purchase_order_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='receptionorder',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
