# Generated by Django 4.2.3 on 2023-11-02 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0013_releasedto'),
        ('wareHouse', '0011_receptionorder_charges_receptionorder_invoice_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
                ('number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('creation_date', models.DateField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('pro_number', models.CharField(blank=True, max_length=200, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=200, null=True)),
                ('purchase_order_number', models.CharField(blank=True, max_length=200, null=True)),
                ('commodities', models.JSONField(blank=True, null=True)),
                ('charges', models.JSONField(blank=True, null=True)),
                ('disabled', models.BooleanField(default=False)),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='releaseCarrier', to='maintenance.carrier')),
                ('client_to_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='releaseclientToBill', to='maintenance.releasedto')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='releaseEmployee', to='maintenance.employee')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='releaseAgent', to='maintenance.agent')),
                ('released_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='releaseReleaseTo', to='maintenance.releasedto')),
                ('warehouse_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pickupOrder', to='wareHouse.pickuporder')),
            ],
        ),
    ]
