# Generated by Django 4.2.3 on 2023-09-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='TypePerson',
            field=models.CharField(default='Customer', max_length=200),
        ),
    ]
