# Generated by Django 4.2.3 on 2023-11-10 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("maintenance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clienttobill",
            name="agent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="client_agent",
                to="maintenance.agent",
            ),
        ),
        migrations.AddField(
            model_name="clienttobill",
            name="agentid",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="clienttobill",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="client_customer",
                to="maintenance.customer",
            ),
        ),
        migrations.AddField(
            model_name="clienttobill",
            name="customerid",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
