# Generated by Django 4.2.3 on 2023-09-25 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_shipper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipper',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='shipper',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='shipper',
            name='vendor',
        ),
    ]
