# Generated by Django 4.2.3 on 2023-09-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_alter_customer_typeperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('fax', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('identification_number', models.CharField(blank=True, max_length=200, null=True)),
                ('identification_type', models.CharField(blank=True, max_length=200, null=True)),
                ('street_and_number', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=200, null=True)),
                ('type_person', models.CharField(blank=True, default='agent', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('length', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('volume', models.FloatField(blank=True, null=True)),
                ('max_weight', models.FloatField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('type_code', models.CharField(blank=True, max_length=200, null=True)),
                ('container_code', models.CharField(blank=True, max_length=200, null=True)),
                ('container_type', models.CharField(blank=True, max_length=200, null=True)),
                ('ground', models.BooleanField(blank=True, default=False, null=True)),
                ('air', models.BooleanField(blank=True, default=False, null=True)),
                ('ocean', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='address',
        ),
        migrations.DeleteModel(
            name='addressInfo',
        ),
        migrations.DeleteModel(
            name='companyInfo',
        ),
        migrations.DeleteModel(
            name='companyLogo',
        ),
        migrations.DeleteModel(
            name='companyRegisCode',
        ),
        migrations.DeleteModel(
            name='companyType',
        ),
        migrations.RemoveField(
            model_name='consignee',
            name='customerId',
        ),
        migrations.RemoveField(
            model_name='consignee',
            name='forwarAgentId',
        ),
        migrations.RemoveField(
            model_name='consignee',
            name='vendorId',
        ),
        migrations.DeleteModel(
            name='containerCode',
        ),
        migrations.DeleteModel(
            name='containerEquipType',
        ),
        migrations.DeleteModel(
            name='containerType',
        ),
        migrations.DeleteModel(
            name='importSchedule',
        ),
        migrations.DeleteModel(
            name='packType',
        ),
        migrations.DeleteModel(
            name='systCurren',
        ),
        migrations.DeleteModel(
            name='wareHouseProviders',
        ),
        migrations.RenameField(
            model_name='carrier',
            old_name='airlineCode',
            new_name='airline_code',
        ),
        migrations.RenameField(
            model_name='carrier',
            old_name='airlinePrefix',
            new_name='airline_prefix',
        ),
        migrations.RenameField(
            model_name='carrier',
            old_name='airwayBillNumbers',
            new_name='airway_bill_number',
        ),
        migrations.RenameField(
            model_name='carrier',
            old_name='carrierCode',
            new_name='carrier_code',
        ),
        migrations.RenameField(
            model_name='carrier',
            old_name='carrierType',
            new_name='carrier_type',
        ),
        migrations.RenameField(
            model_name='carrier',
            old_name='firstNameContac',
            new_name='contact_first_name',
        ),
        migrations.RenameField(
            model_name='carrier',
            old_name='lasNameContac',
            new_name='contact_last_name',
        ),
        migrations.RenameField(
            model_name='carrier',
            old_name='iataCode',
            new_name='iata_code',
        ),
        migrations.RenameField(
            model_name='carrier',
            old_name='numIdentification',
            new_name='identification_number',
        ),
        migrations.RenameField(
            model_name='carrier',
            old_name='typeIdentificacion',
            new_name='identification_type',
        ),
        migrations.RenameField(
            model_name='carrier',
            old_name='methodCode',
            new_name='method_code',
        ),
        migrations.RenameField(
            model_name='carrier',
            old_name='movelPhone',
            new_name='mobile_phone',
        ),
        migrations.RenameField(
            model_name='carrier',
            old_name='passengerOnlyAirline',
            new_name='passenger_only_airline',
        ),
        migrations.RenameField(
            model_name='carrier',
            old_name='referentNumber',
            new_name='reference_number',
        ),
        migrations.RenameField(
            model_name='carrier',
            old_name='scacNumber',
            new_name='scac_number',
        ),
        migrations.RenameField(
            model_name='carrier',
            old_name='streetNumber',
            new_name='street_and_number',
        ),
        migrations.RenameField(
            model_name='carrier',
            old_name='TypePerson',
            new_name='type_person',
        ),
        migrations.RenameField(
            model_name='carrier',
            old_name='webSide',
            new_name='website',
        ),
        migrations.RenameField(
            model_name='carrier',
            old_name='zipCode',
            new_name='zip_code',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='firstNameContac',
            new_name='contact_first_name',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='lasNameContac',
            new_name='contact_last_name',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='numIdentification',
            new_name='identification_number',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='telephon',
            new_name='mobile_phone',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='nameCompany',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='webSide',
            new_name='website',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='firstNameContac',
            new_name='contact_first_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='lasNameContac',
            new_name='contact_last_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='numIdentification',
            new_name='identification_number',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='typeIdentificacion',
            new_name='identification_type',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='mobilePhone',
            new_name='mobile_phone',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='referentNumber',
            new_name='reference_number',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='webSide',
            new_name='website',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='zipCode',
            new_name='zip_code',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='firstNameContac',
            new_name='contact_first_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='lasNameContac',
            new_name='contact_last_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='numIdentification',
            new_name='identification_number',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='typeIdentificacion',
            new_name='identification_type',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='movelPhone',
            new_name='mobile_phone',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='referentNumber',
            new_name='reference_number',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='webSide',
            new_name='website',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='zipCode',
            new_name='zip_code',
        ),
        migrations.RenameField(
            model_name='port',
            old_name='subdivision',
            new_name='sub_division',
        ),
        migrations.RenameField(
            model_name='port',
            old_name='usCustomsCode',
            new_name='us_customs_code',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='firstNameContac',
            new_name='contact_first_name',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='lasNameContac',
            new_name='contact_last_name',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='numIdentification',
            new_name='identification_number',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='typeIdentificacion',
            new_name='identification_type',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='movelPhone',
            new_name='mobile_phone',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='referentNumber',
            new_name='reference_number',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='webSide',
            new_name='website',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='zipCode',
            new_name='zip_code',
        ),
        migrations.RemoveField(
            model_name='carrier',
            name='parentAccount',
        ),
        migrations.RemoveField(
            model_name='carrier',
            name='sistenID',
        ),
        migrations.RemoveField(
            model_name='company',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='company',
            name='idEntity',
        ),
        migrations.RemoveField(
            model_name='company',
            name='idNetWord',
        ),
        migrations.RemoveField(
            model_name='company',
            name='numCuent',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='TypePerson',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='sistenID',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='streetNumber',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='TypePerson',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='sistenID',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='streetNumber',
        ),
        migrations.RemoveField(
            model_name='location',
            name='disable',
        ),
        migrations.RemoveField(
            model_name='location',
            name='maxWeight',
        ),
        migrations.RemoveField(
            model_name='port',
            name='TypePerson',
        ),
        migrations.RemoveField(
            model_name='port',
            name='borderCrossing',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='TypePerson',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='sistenID',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='streetNumber',
        ),
        migrations.AddField(
            model_name='company',
            name='account_number',
            field=models.CharField(blank=True, default='none', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_fmc_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_iata_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_img_logo',
            field=models.ImageField(blank=True, null=True, upload_to='./logo'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_img_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_scac_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_tsa_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='port',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='street_and_number',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='type_airline_carrier',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='type_company_warehouse',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='type_distribution',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='type_logistic_provider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='type_ocean_carrier',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='zip_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='street_and_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='type_person',
            field=models.CharField(blank=True, default='customer', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='street_and_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='type_person',
            field=models.CharField(blank=True, default='employee', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='disabled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='max_weight',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='port',
            name='border_crossing',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='port',
            name='type_person',
            field=models.CharField(blank=True, default='port', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='street_and_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='type_person',
            field=models.CharField(blank=True, default='vendor', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='empty',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='height',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='length',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='volume',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='weight',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='width',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='port',
            name='air',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='port',
            name='mail',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='port',
            name='maritime',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='port',
            name='name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='port',
            name='rail',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='port',
            name='road',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='port',
            name='used',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.DeleteModel(
            name='consignee',
        ),
    ]
