# Generated by Django 4.2.3 on 2023-09-15 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_alter_customer_typeperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignee',
            name='vendorId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='consigneeVendor', to='maintenance.vendor'),
        ),
    ]
