# Generated by Django 4.2.3 on 2023-09-22 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wareHouse', '0005_rename_creationdate_pickuporder_creation_date_and_more'),
        ('maintenance', '0004_agent_packagetype_delete_address_delete_addressinfo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='forWardingAgents',
        ),
    ]
