# Generated by Django 4.2.3 on 2023-09-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_delete_forwardingagents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='height',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='length',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='max_weight',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='volume',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='weight',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='width',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
    ]
