# Generated by Django 4.2.3 on 2023-10-03 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_consignee_agentid_consignee_carrierid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientToBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipperid', models.CharField(blank=True, max_length=200, null=True)),
                ('consigneeid', models.CharField(blank=True, max_length=200, null=True)),
                ('consignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_consignee', to='maintenance.consignee')),
                ('shipper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_shipper', to='maintenance.shipper')),
            ],
        ),
    ]
