# Generated by Django 4.2.3 on 2023-10-04 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0009_clienttobill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipper',
            name='agentid',
        ),
        migrations.RemoveField(
            model_name='shipper',
            name='customerid',
        ),
        migrations.RemoveField(
            model_name='shipper',
            name='data',
        ),
        migrations.RemoveField(
            model_name='shipper',
            name='vendorid',
        ),
    ]
