# Generated by Django 4.2.3 on 2023-10-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0010_remove_shipper_agentid_remove_shipper_customerid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipper',
            name='agentid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shipper',
            name='customerid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shipper',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipper',
            name='vendorid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
