# Generated by Django 4.2.3 on 2023-10-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0011_shipper_agentid_shipper_customerid_shipper_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienttobill',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
