# Generated by Django 4.2.3 on 2023-11-02 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0012_clienttobill_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReleasedTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerid', models.CharField(blank=True, max_length=200, null=True)),
                ('vendorid', models.CharField(blank=True, max_length=200, null=True)),
                ('carrierid', models.CharField(blank=True, max_length=200, null=True)),
                ('agentid', models.CharField(blank=True, max_length=200, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='releasedto_agent', to='maintenance.agent')),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='releasedto_carrier', to='maintenance.carrier')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='releasedto_customer', to='maintenance.customer')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='releasedto_vendor', to='maintenance.vendor')),
            ],
        ),
    ]
