# Generated by Django 4.2.6 on 2023-11-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chartAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('referenceNum', models.BigIntegerField(blank=True, null=True)),
                ('balanceUSD', models.BigIntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=100, null=True)),
                ('parentAccount', models.CharField(blank=True, max_length=100, null=True)),
                ('accountNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=200, null=True)),
                ('account', models.CharField(blank=True, max_length=200, null=True)),
                ('paymentTem', models.CharField(blank=True, max_length=200, null=True)),
                ('division', models.CharField(blank=True, max_length=200, null=True)),
                ('apply', models.CharField(blank=True, max_length=200, null=True)),
                ('due', models.DateField(blank=True, null=True)),
                ('trasaDate', models.DateField(blank=True, null=True)),
                ('bilingAddres', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=200, null=True)),
                ('issuedById', models.CharField(blank=True, max_length=200, null=True)),
                ('issuedByName', models.CharField(blank=True, max_length=200, null=True)),
                ('invoiceById', models.CharField(blank=True, max_length=200, null=True)),
                ('invoiceBydescription', models.CharField(blank=True, max_length=200, null=True)),
                ('paymentById', models.CharField(blank=True, max_length=200, null=True)),
                ('paymentByDesc', models.CharField(blank=True, max_length=200, null=True)),
                ('accountById', models.CharField(blank=True, max_length=200, null=True)),
                ('accountByName', models.CharField(blank=True, max_length=200, null=True)),
                ('accountByType', models.CharField(blank=True, max_length=200, null=True)),
                ('paidAdd', models.CharField(blank=True, max_length=200, null=True)),
                ('exchangeRate', models.BigIntegerField(blank=True, null=True)),
                ('amount', models.BigIntegerField(blank=True, null=True)),
                ('totalAmount', models.BigIntegerField(blank=True, null=True)),
                ('invoiceCharges', models.JSONField(blank=True, null=True)),
                ('taxCode', models.BigIntegerField(blank=True, null=True)),
                ('amountDue', models.BigIntegerField(blank=True, null=True)),
                ('charges', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('accountName', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('autCreation', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(blank=True, max_length=100, null=True)),
                ('iataCode', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='openingBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('balance', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
