# Generated by Django 5.0 on 2024-01-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposits',
            name='depositCharges',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
