# Generated by Django 4.2.3 on 2023-11-02 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartaccounts',
            name='balanceUSD',
        ),
        migrations.RemoveField(
            model_name='chartaccounts',
            name='referenceNum',
        ),
        migrations.AddField(
            model_name='chartaccounts',
            name='accountNumber',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chartaccounts',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chartaccounts',
            name='currency',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chartaccounts',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chartaccounts',
            name='parentAccount',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='chartaccounts',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
