# Generated by Django 4.2.6 on 2023-11-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='accounten',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
