# Generated by Django 4.2.3 on 2023-11-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_remove_chartaccounts_balanceusd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=200, null=True)),
                ('account', models.CharField(blank=True, max_length=200, null=True)),
                ('paymentTem', models.CharField(blank=True, max_length=200, null=True)),
                ('division', models.CharField(blank=True, max_length=200, null=True)),
                ('apply', models.CharField(blank=True, max_length=200, null=True)),
                ('due', models.DateField(blank=True, null=True)),
                ('trasaDate', models.DateField(blank=True, null=True)),
                ('bilingAddres', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=200, null=True)),
                ('issuedById', models.CharField(blank=True, max_length=200, null=True)),
                ('issuedByName', models.CharField(blank=True, max_length=200, null=True)),
                ('invoiceById', models.CharField(blank=True, max_length=200, null=True)),
                ('invoiceBydescription', models.CharField(blank=True, max_length=200, null=True)),
                ('paymentById', models.CharField(blank=True, max_length=200, null=True)),
                ('paymentByDesc', models.CharField(blank=True, max_length=200, null=True)),
                ('paidAdd', models.CharField(blank=True, max_length=200, null=True)),
                ('exchangeRate', models.BigIntegerField(blank=True, null=True)),
                ('amount', models.BigIntegerField(blank=True, null=True)),
                ('totalAmount', models.BigIntegerField(blank=True, null=True)),
                ('invoiceCharges', models.JSONField(blank=True, null=True)),
                ('taxCode', models.BigIntegerField(blank=True, null=True)),
                ('amountDue', models.BigIntegerField(blank=True, null=True)),
                ('charges', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='chartaccounts',
            name='balanceUSD',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chartaccounts',
            name='referenceNum',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chartaccounts',
            name='accountNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chartaccounts',
            name='currency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chartaccounts',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chartaccounts',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chartaccounts',
            name='parentAccount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chartaccounts',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
