# Generated by Django 4.2.6 on 2023-11-21 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_invoice_issuedbyid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='issuedById',
            new_name='issued_by',
        ),
    ]
