# Generated by Django 4.2.6 on 2023-11-04 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_invoice_accounten'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='typeByCode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
