# Generated by Django 5.0 on 2024-01-15 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_deposits_depositcharges'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposits',
            name='total',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
