# Generated by Django 4.2.3 on 2023-11-08 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_invoice_chartaccounts_balanceusd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='accountById',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='accountByName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='accountByType',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='accounten',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='typeByCode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
