# Generated by Django 4.2.6 on 2023-11-22 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
        ('accounting', '0003_rename_issuedbyid_invoice_issued_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='paymentById',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='configuration.paymentterms'),
        ),
    ]
