# Generated by Django 4.2.6 on 2023-11-22 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_invoice_paymentbyid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='accountById',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.chartaccounts'),
        ),
    ]
