# Generated by Django 4.2.6 on 2023-11-25 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
        ('accounting', '0005_alter_invoice_accountbyid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='accounten',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='amountDue',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='applyId',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='charges',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='taxCode',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='totalAmount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='typeChart',
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.customer')),
            ],
        ),
    ]
