# Generated by Django 4.2.6 on 2023-11-25 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_remove_invoice_accounten_remove_invoice_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='customer',
            new_name='customerById',
        ),
    ]
