# Generated by Django 4.2.6 on 2023-11-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_rename_customer_payments_customerbyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='customerByName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
