# Generated by Django 4.2.6 on 2023-11-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_payments_customerbyname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='customerById',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
