# Generated by Django 4.2.6 on 2023-11-27 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
        ('accounting', '0009_alter_payments_customerbyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='amountReceived',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='payments',
            name='customerById',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='maintenance.customer'),
        ),
    ]
