# Generated by Django 4.2.6 on 2023-11-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_payments_amountreceived_alter_payments_customerbyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='due',
            field=models.DateField(blank=True, null=True),
        ),
    ]
