# Generated by Django 4.2.6 on 2023-11-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_payments_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
