# Generated by Django 4.2.6 on 2023-11-27 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_payments_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='due',
            new_name='transaction',
        ),
    ]
