# Generated by Django 4.2.6 on 2023-11-27 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_rename_due_payments_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='transaction',
            new_name='transactionDate',
        ),
    ]
