# Generated by Django 4.2.6 on 2023-11-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_rename_transaction_payments_transactiondate'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='transaction_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
