# Generated by Django 4.2.6 on 2023-11-28 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_payments_transaction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='transaction_Date',
        ),
    ]
