# Generated by Django 4.2.6 on 2023-11-28 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_remove_payments_transaction_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='transactionDate',
            new_name='trasaDate',
        ),
    ]
