# Generated by Django 4.2.6 on 2023-11-28 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_rename_transactiondate_payments_trasadate'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='memo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
