# Generated by Django 4.2.6 on 2023-11-29 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_payments_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='inviceData',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounting.invoice'),
        ),
    ]
