# Generated by Django 4.2.3 on 2023-11-30 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_payments_invicedata'),
        ('accounting', '0019_payments_invoicedata'),
    ]

    operations = [
    ]
